import {
  LayoutDashboard,
  Users,
  Settings,
  CreditCard,
  ChevronLeft,
  ChevronRight,
  MoreHorizontal,
  PlusCircle,
  Search,
  Trash2,
  Edit3,
  Eye,
  LogOut,
  DollarSign,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  UserCircle,
  Menu,
  Moon,
  Sun,
  BarChart,
  PieChart,
  FileText,
  Mail,
  Bell,
  MapPin,
  Briefcase,
} from 'lucide-react';

export const Icons = {
  logo: Briefcase, // Using Briefcase as a placeholder logo icon
  dashboard: LayoutDashboard,
  clients: Users,
  settings: Settings,
  payments: CreditCard,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  moreHorizontal: MoreHorizontal,
  add: PlusCircle,
  search: Search,
  delete: Trash2,
  edit: Edit3,
  view: Eye,
  logout: LogOut,
  dollarSign: DollarSign,
  warning: AlertTriangle,
  success: CheckCircle2,
  error: XCircle,
  user: UserCircle,
  menu: Menu,
  moon: Moon,
  sun: Sun,
  barChart: BarChart,
  pieChart: PieChart,
  fileText: FileText,
  mail: Mail,
  bell: Bell,
  mapPin: MapPin,
};
